|***
 * TestSuite.mac
 * MQ2RaidType.cpp
 * testing MQ2RaidType
 *
 ***|








sub start_MQ2RaidType()
	/echo
	OUT Testing::\awMQ2RaidType\ax (\a-tRaid.\ax)
	LOG
	LOG Testing::MQ2RaidType



| Locked
| Invited
| xMember
| ${Raid.Member}
| Members
| Target
| Leader
| TotalLevels
| AverageLevel
| Looters
| Looter
| MainAssist
| MasterLooter
|
|
|
|
|
|
|
|
|
|
|
|







/return



${Raid.}
${Raid.}
${Raid.}
${Raid.}
${Raid.}
